clearlinux/dockerfiles

keystone/keystone.wsgi.conf

nginx in clearlinux supports http2
This commit enables this feature for improved speed.
Signed-off-by: Alberto Murillo <alberto.murillo.silva@intel.com>

keystone: Enable http2

---

README.md
ciao-deploy/Dockerfile
ciao-deploy/README.md

This commits adds a dockerfile useful to create a
container which fulfills all the requirements for
the deployment node in a ciao cluster setup.
By using the `ciao-deploy` container, operator shouldn't
require to install anything else in order to get a ciao
deployment node.

Add `ciao-deploy` Dockerfile

---

ciao-deploy/Dockerfile

the kvm-host bundle was added to include the qemu-nbd tool,
since this is not neccessary for the ciao-deployment, we can
get rid of this bundle.

ciao-deploy: remove kvm-host bundle install

---

ciao-deploy/Dockerfile

previous to this change, there was no explicit requirement
of the openssl tools. The cryptography bundle provides this
functionality.

ciao-deploy: Add cryptography bundle

---

machine-learning/Dockerfile
machine-learning/README.md

This commits adds a Dockerfile to create a machine-learning docker container,
useful to develop machine-learning solutions based on R language and
other python packages such as scipy, scikit-learn and others.

Add `machine-learning` Dockerfile

---

ciao-deploy/Dockerfile
ciao-deploy/README.md

By delegating the cluster configuration out of the
container, those will be persistent, allowing the user to
keep them for a future reference/re-deployment.

ciao-deploy: delegate the file edits out of the container

---

ciao-deploy/Dockerfile

With previous change, the clearlinux roles on the docker image
are not correctly installed

ciao-deploy: fix ansible install of playbooks

---

ciao-deploy/README.md

Since the ciao examples to deploy were moved
from https://github.com/clearlinux/clear-config-management
to https://github.com/01org/ciao/, the instructions
should tell the user to use the ciao ones instead of
deprecated clear-config-management.

ciao-deploy: use ciao provided ansible playbooks

---

ciao-deploy/Dockerfile

Base clearlinux image has changed and now openstack-common bundle
was refactored, this change removes `/usr/bin/openstack`, hence
`openstack-python-clients` bundle is needed in order to perform
operations using the openstack CLI.

ciao-deploy: install `openstack-python-clients` bundle

---

ciao-deploy/README.md

As the container use `/usr/bin/losetup` to manipulate the
CNCI image, it's neccessary to use the container in
`--privileged` mode and map `/dev/`, otherwise the container
won't be able to perfomr `losetup` operation nor mount the loops.
this commit updates the documentation to instruct the user how
to call the container in privileged mode.
This commit fixes #16

ciao-deploy: update documentation to use privileged container

---

ciao-deploy/Dockerfile

This is a cleanup commit; since the documentation ask the user
to map the github.com/01org/ciao repository directly into the
ciao-deploy container, it's not neccessary to install the roles
from ansible-galaxy anymore due to those roles being used by
ansible directly from the ciao repo.
The `openstack-common` bundle is removed from the
`swupd bundle-add` command because the `openstack-python-clients`
bundle already includes it implicit.
This commit fixes #14

ciao-deploy: don't install roles from ansible galaxy

---

.travis.yml
README.md
keystone/verify-keystone.sh

We need an automated way of testing our new Docker containers in
order to make sure content is working as expected.
This commits introduces initial tests for Keystone docker container.
Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>

travis: Add initial CI integration

---

ciao-deploy/README.md

README.md is ambiguous with 2 options of how to call the
ciao-deploy container (one with private ssh-key and other
without it), this may confuse the user.
This commit just mention 1 instruction to launch the
ciao-deploy container.
This commit fixes #15

ciao-deploy: update readme to instruct user to use ssh key

---

keystone/verify-keystone.sh

Added testing for operations with roles, ec2 credentials, users, projects, endpoints, and services, those tests were formally execute for keystone in clearlinux for the openstack project

keystone: Add extra tests cases for keystone operations

---

ciao-scheduler/configuration.yaml

This patch set updates the configuration file which is included by default in the ciao-scheduler container, removing unused fields in the configuration file and fixing the location of the storage_uri.

Ciao config update

---

README.md
clr-sdk/Dockerfile
clr-sdk/README.md
clr-sdk/clruser
clr-sdk/setup.py

Docker container for running Clear Linux developer tooling.
Allows a user to run mixer tool in a cross-platform way.
Built atop the clearlinux:latest image, and includes the
os-clr-on-clr bundle for devloper tools. A python script
sets up up a non-root user (with UID & GID mapped to the
mix directory mounted at runtime), with sudo privileges
only for mixer, swupd, and mock.
Note: The README mentions privileges needed to run mixer
build-image. This is sufficient for now, and narrowing
the --privileged to the specific CAP subset (SYS_ADMIN,
MKNOD, etc?) is left for a future task.
Signed-off-by: Kevin C. Wells <kevin.c.wells@intel.com>

Create clr-sdk Docker Container.

---

README.md
mixer-ci/Dockerfile
mixer-ci/README.md

This patch introduces an image used for running the Mixer CI on Travis.
Previously, a very large part of the time Travis spent building and
validating Mixer PR's was spent 'swupd bundle-add'ing the packages
needed. The _mixer_ build was very short once this step was done.
This image removes the need to build and configure the image with each
Travis run; only the code needs to be copied over before the mixer
build and tests can run.
Signed-off-by: Kevin C. Wells <kevin.c.wells@intel.com>

Add clearlinux/mixer-ci Docker Image

---

stacks/dlaas/README.md
stacks/dlaas/mkl/README.md
stacks/dlaas/oss/README.md

Changes name from Clear Linux Deep Learning Stack to Intel Deep Learning Stack in the README.md files.

updating 3 README files with Stack name change 

---

stacks/dlrs/mkl/setup_mkl.sh

Two changes to the mkl dockerfiles
- Change channel to intel for tensorflow
- Remove sym links that are not required
Closes: #56

Removing links and add intel as the channel to download from

---

stacks/dlrs/mkl/setup_mkl.sh

There is a perf regression for Tensorflow from intel channel, switching to anaconda channel for TF.
Closes: #62

switching to official anaconda channel

---

stacks/dlrs/releasenote.md

A message stating that the TensorFlow used by the
stacks-dlrs-mkl image does not support AVX instructions
can be missleading for users.
This change adds a note clarifying how the performance
optimization is handled in this image.
Signed-off-by: Jose Lamego <jose.a.lamego@intel.com>

releasenote.md: Add note for no-avx-support message

---

stacks/dlrs/mkl/Dockerfile
stacks/dlrs/mkl/README.md
stacks/dlrs/oss/Dockerfile
stacks/dlrs/oss/README.md
stacks/dlrs/releasenote.md

The stacks team validates a certain Clear Linux OS version, to ensure functionality, such version must be provided and used within the Dockerfiles. The releasenotes and readme files should also reflect the change.
Fixes #65

Using latest validated Clear Linux OS version in Dockerfiles

---

stacks/dlrs/kubeflow/dlrs-tfjob/dlrs-bench/prototypes/dlrs-alexnet.jsonnet
stacks/dlrs/kubeflow/dlrs-tfjob/dlrs-bench/prototypes/dlrs-resnet50.jsonnet

The image name was hardcoded. We should receive a variable with the
image name instead, this will let the end user select which DLRS
flavour (mkl or oss) to use.

prototypes: sets up ks prototypes to receive image names as parameter

---

stacks/dlrs/releasenote.md

Updating the security reporting text to reflect changes from OSSIRT to iPSIRT.

Update 'Reporting Security Issues' in releasenotes

---

stacks/dlrs/mkl/setup_mkl.sh

There is no sense to ship caches and downloaded archives in the container.
Cleaning it will save about 500Mb

Cleanup miniconda caches after environment is created

---

cgit/README.md
clr-sdk/README.md
elasticsearch/README.md
httpd/README.md
machine-learning-ui/README.md
machine-learning/README.md
mariadb/README.md
memcached/README.md
nginx/README.md
postgres/README.md
python/README.md
redis/README.md
stacks/dlrs/mkl/README.md
stacks/dlrs/oss/README.md
stacks/dlrs/pytorch/mkl/README.md
stacks/dlrs/pytorch/oss/README.md

There are some broken links in the various `README.md` files, and some of the links point to clearlinux.org when they can instead point directly to the swupd-client github repo for the latest information. This PR addresses these issues.

Fix some hyperlinks

---

README.md

Browsing through the folder directory structure is always a current
means to identify which images are being published on Docker Hub.  Would
no longer need to keep another list in sync.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>

Remove image list from README

---

nginx/Dockerfile
nginx/default.conf

This PR: 
- Fixes issue https://github.com/clearlinux/dockerfiles/issues/112 where the access.log is not working.
- Flattens the Dockerfile by combining RUN instructions to minimize image layers/size.

Update nginx container 

---

cgit/Dockerfile
elasticsearch/Dockerfile
haproxy/Dockerfile
httpd/Dockerfile
iperf/Dockerfile
mariadb/Dockerfile
memcached/Dockerfile
nginx/Dockerfile
node/Dockerfile
openjdk/Dockerfile
php/Dockerfile
postgres/Dockerfile
python/Dockerfile
redis/Dockerfile
ruby/Dockerfile

To help analyze the container image size by layers, assume
each container image be comprised of:
Layer 1: clearlinux:latest
Layer 2: swupd update
Other layers: the container configurations
With this, we can continue to optimize layer size accordingly.

Make the swupd update always be the layer two

---

clr-installer-ci/Dockerfile

We were still using the older ister bundle to install dependencies and then augmenting during the TravisCI run.

clr-installer-ci: update bundles

---

clr-installer-ci/Dockerfile

Missed the development libraries needed for building, but not for running.

clr-installer-ci: Add the GTK development support

---

cgit/Dockerfile
httpd/Dockerfile
memcached/Dockerfile
nginx/Dockerfile
os-core/Dockerfile
os-core/README.md
redis/Dockerfile

Use a docker multistage build technique to create a container
that only has the os-core bundle, providing the minimal content
required for constructing any Clear Linux base container.
Any containers that use this as a common base and still require
additional Clear Linux content will also need to perform a
multistage build since the os-core container does not include
swupd.
Signed-off-by: Rusty Lynch <rusty.lynch@intel.com>

Create minimal base layer container

---

mariadb/Dockerfile

Convert mariadb container to be based on the minimal os-core
container, using a multistage build technique to add additional
Clear Linux content.
Signed-off-by: Rusty Lynch<rusty.lynch@intel.com>

Minimize mariadb container using the os-core container.

---

postgres/Dockerfile

Convert postgres container to be based on the minimal os-core
container, using a multistage build technique to add additional
Clear Linux content.

Minimize postgres container size using the os-core container

---

redis/Dockerfile

For some Host OS configuration with redirect_dir on,
extra data are saved on the upper layer when the same
file exists on different layers. To minimize docker
image size, remove the overlapped files before copy.

only copy delta files when multistage build

---

cgit/Dockerfile
elasticsearch/Dockerfile
flink/Dockerfile
haproxy/Dockerfile
httpd/Dockerfile
iperf/Dockerfile
mariadb/Dockerfile
memcached/Dockerfile
nginx/Dockerfile
postgres/Dockerfile

For some Host OS configuration with redirect_dir on,
extra data are saved on the upper layer when the same
file exists on different layers. To minimize docker
image size, remove the overlapped files before copy.

only copy delta files during multistage build

---

golang/Dockerfile
node/Dockerfile
openjdk/Dockerfile
perl/Dockerfile
php/Dockerfile
python/Dockerfile
rabbitmq/Dockerfile
ruby/Dockerfile
tensorflow/Dockerfile

Convert golang, node, openjdk, perl, php, python,
rabbitmq, ruby and tensorflow containers to be based
on the minimal os-core container, using a multistage
build technique to add additional Clear Linux content.

Minimize containers size using the os-core container

---

flink/Dockerfile

Enable swupd for flink as it needs to install
java and other bundles most of the time.

enable swupd function for flink container

---

cassandra/Dockerfile
cgit/Dockerfile
elasticsearch/Dockerfile
flink/Dockerfile
golang/Dockerfile
haproxy/Dockerfile
httpd/Dockerfile
iperf/Dockerfile
mariadb/Dockerfile
memcached/Dockerfile
nginx/Dockerfile
node/Dockerfile
openjdk/Dockerfile
perl/Dockerfile
php-fpm/Dockerfile
php/Dockerfile
postgres/Dockerfile
python/Dockerfile
rabbitmq/Dockerfile
redis/Dockerfile
ruby/Dockerfile
tensorflow/Dockerfile

When removing the duplicated file and directory via rm -d,
if it's a non-empty directory, it will prompt the warning
message that the directory could not be removed becuase it
is not empty. This is as expectation, as there are other
files under the same diretory and we need to keep them.
Hide these warning message to avoid confusion.

Hide the expected warning msg

---

redis/Dockerfile
redis/docker-entrypoint.sh

The redis on docker hub disabled protected mode in default.
To make clear redis be compatible, disable the protected mode
in default as well.

Disable redis protected mode

---

cgit/Dockerfile

clearlinux/cgit is based on clearlinux/httpd, so it's better
to build it based on clearlinux/httpd's clearlinux version,
to avoid the dependenc that both clearlinux/os-core and
clearlinux/httpd must be the same version. Also to reduce
the container size further.

make cgit inherits the httpd's clearlinux version

---

machine-learning-ui/Dockerfile
machine-learning-ui/README.md
machine-learning-ui/jupyter_notebook_config.py
machine-learning/Dockerfile

Squash all RUN commands to a single line so that it results in a
single docker layer.  Adding a new RUN command to remove files
will result in the files not being visible in the container, but
users still carry the full weight of the "deleted" files.
Signed-off-by: Rusty Lynch <rusty.lynch@intel.com>

Cleanup machine-learning RUN commands

---

.travis.yml

Currently this isn't actively being worked on so having it being
tested just causes false positives due to timeouts building the
container. Look at adding it back once the build time can be reduced.

Remove clr-sdk from travis to avoid timeouts

---

cassandra/Dockerfile
cassandra/docker-entrypoint.sh
elasticsearch/Dockerfile
elasticsearch/docker-entrypoint.sh
mariadb/Dockerfile
mariadb/docker-entrypoint.sh
memcached/Dockerfile
memcached/docker-entrypoint.sh
postgres/Dockerfile
postgres/bootstrap.sh
rabbitmq/Dockerfile
rabbitmq/docker-entrypoint.sh
redis/Dockerfile
redis/docker-entrypoint.sh

With su-exec, make sure the SIGTERM upon docker stop
could be received by the running program thus causing
a clean stop/exit.
Signed-off-by: Qi Zheng <qi.zheng@intel.com> 
#181 
#184

Use su-exec to run commands on entryponit

---

cassandra/Dockerfile
cgit/Dockerfile
httpd/Dockerfile
mariadb/Dockerfile
memcached/Dockerfile
nginx/Dockerfile
os-core/Dockerfile
redis/Dockerfile

During the 1st stage build of multi-stage build, when
run swupd os-install, the swupd state data are saved to
/swupd_state, which will not be copied to the target.
So we do not need to remove swupd state data.

no swupd state data removing in 1st build stage

---

nginx/Dockerfile

Use --no-boot-update instead of --no-scripts for nginx.

Use --no-boot-update for nginx

---

nginx/README.md

Change relative URLs to full. Relative URLs don't render on hub.docker.com

Fix URLS in nginx README

---

node/Dockerfile
node/docker-entrypoint.sh

Create link for /usr/bin/yarn, which is the same as the official
docker. Add docker_entrypoint.sh as official one.

add docker_entrypoint as official

---

mixer-ci/Dockerfile

gometalinter has been deprecated in favor of golangci.
This patch changes the linter used in mixer to the new one.
Signed-off-by: Rodrigo Chiossi <rodrigo.chiossi@intel.com>

mixer-ci: Use golangci instead of gometalinter

---

stacks/dbrs/cassandra/Dockerfile
stacks/dbrs/redis/Dockerfile

This PR includes 2 commits to update the Dockerfiles for stacks-dbrs-redis and stacks-dbrs-cassandra.
Avoid large bundle for stacks-dbrs-redis build:
The package libnuma is required for Redis stack, the bundle which has
this package is os-testsuite-phoronix, however, the size is too large.
In order to avoid downloading the whole bundle, the package can be
downloaded from Clear Linux published RPMs, this will save network
bandwidth and build time.
Add snappy to stacks-dbrs-cassandra image
Snappy is a library used for data compression, it is not stritctly
required by Cassandra but can be very useful for large datasets.
Signed-off-by: Gabriel Briones <gabriel.briones.sayeg@intel.com>

Update DBRS v0.1.0 dockerfiles

---

mixer-ci/Dockerfile

Sudo is required to run bat tests.
Signed-off-by: Rodrigo Chiossi <rodrigo.chiossi@intel.com>

mixer-ci: add sudo

---

docker-hooks.sh
redis/hooks/post_push

Using the docker build hooks way to tag the redis image.
https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks
Adding post_push script to do the tag with below steps.
1. Get container Clear Linux version from clearlinux/os-core because all the other containers are built on top of the clearlinux/os-core thus they have the same version.
2. Parse the "package-sources" file from that release version to get the app version according to the package name. In this case it is package redis-native.
3. Tag the latest container image with tag acquired on step 2 and push it.
4. Also tag it "major_tag" and push it. "major_tag" means the major version. 
For example, we got tag "5.0.6" in step 2, then the "major_tag" is "5".
For deleting …

Add post_push hooks to tag with redis version

---

docker-hooks.sh
golang/hooks/post_push
haproxy/hooks/post_push
httpd/hooks/post_push
iperf/hooks/post_push
mariadb/hooks/post_push
memcached/hooks/post_push
nginx/hooks/post_push
node/hooks/post_push
openjdk/hooks/post_push
openvino/hooks/post_push
perl/hooks/post_push
php-fpm/hooks/post_push
php/hooks/post_push
postgres/hooks/post_push
python/hooks/post_push
rabbitmq/hooks/post_push
redis/hooks/post_push
ruby/hooks/post_push
tensorflow-serving/hooks/post_push
tensorflow/hooks/post_push

For version format x.y.z, three tags as below
tag: x.y.z
tag1: x.y
tag2: x
They all point to the latest image.
Once app got updated (minor updates, z to z1), the tag x.y.z
will be replaced by x.y.z1, but the tag x or x.y may still
keep.

Unify the tags way
