ciao-webui/Dockerfile, ciao-webui/README.md, ciao-webui/bootstrap.sh, ciao-webui/ciao_config.json
This commit add the `Dockerfile` and other files
needed in order to build a docker image of
the ciao-webui dashboard
=> Add ciao-webui container files

ciao-webui/Dockerfile, ciao-webui/README.md, ciao-webui/bootstrap.sh, ciao-webui/ciao_config.json
This patchset will update the ciao-webui configuration to provide the `storage` section.
It updates the ciao-webui to the latest release as well (1.3.12.15)
=> Ciao webui update

ciao-webui/Dockerfile
Signed-off-by: Alberto Murillo Silva <alberto.murillo.silva@intel.com>
=> ciao-webui: Update to v1.4.13.20

.travis.yml, README.md
Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>
=> travis: Deploy capability is only for master branch

.travis.yml
Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>
=> travis: Add after_success section

.travis.yml, keystone/Dockerfile
Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>
=> travis: Update deploy process

machine-learning-ui/Dockerfile, machine-learning-ui/README.md, machine-learning-ui/jupyter_notebook_config.py
Add an image for the machine-learning-web-ui bundle to give easy
access to a ready to run jupyter based environment.
=> Add new image for machine-learning-web-ui bundle

clr-installer-ci/Dockerfile
Need an additional bundle for proper testing.
Signed-off-by: Mark D Horn <mark.d.horn@intel.com>
=> New bundle required for Clear Linux OS Installer

clr-sdk/README.md
The current link does not resolve.
=> Fix link to mixer guide

.travis.yml
This was my attempt at fixing the issue #31 
I basically got rid of all the tokens etc. (those can be added of course by the owners)
=> Build all containers in .travis.yml

.travis.yml, README.md, stacks/dlaas/README.md, stacks/dlaas/kubeflow/Dockerfile, stacks/dlaas/kubeflow/dlaas-tfjob/dlaas-bench/parts.yaml, stacks/dlaas/kubeflow/dlaas-tfjob/dlaas-bench/prototypes/dlaas-alexnet.jsonnet, stacks/dlaas/kubeflow/dlaas-tfjob/dlaas-bench/prototypes/dlaas-resnet50.jsonnet, stacks/dlaas/kubeflow/dlaas-tfjob/registry.yaml, stacks/dlaas/mkl/Dockerfile, stacks/dlaas/mkl/licenses/README.md, stacks/dlaas/mkl/licenses/clear_LICENSE, stacks/dlaas/mkl/licenses/horovod_LICENSE, stacks/dlaas/mkl/licenses/miniconda_LICENSE, stacks/dlaas/mkl/licenses/mkl_LICENSE, stacks/dlaas/mkl/setup_mkl.sh, stacks/dlaas/oss/Dockerfile, stacks/dlaas/oss/licenses/README.md, stacks/dlaas/oss/licenses/clear_LICENSE, stacks/dlaas/oss/licenses/horovod_LICENSE
This provides a Clear Linux* with the DLaaS (Deep-Learning-as-a-Service)
stack. To offer more flexibility, there are two versions of the Deep Learning
Stack:  a "fully open source" version that includes only open source
components, and a second, "mostly open source" version that includes the
TensorFlow* framework optimized using Intel® Math Kernel Library for Deep
Neural Networks (Intel® MKL-DNN) primitives.
=> dlaas: dockerfiles for Clear Linux* with the DLaaS

stacks/dlaas/kubeflow/launcher.py
=> Adds launcher.py as it is required by the Dockerfile

stacks/dlaas/README.md, stacks/dlaas/mkl/README.md, stacks/dlaas/oss/README.md
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
=> Fix readme for initial stacks drop

stacks/dlaas/README.md, stacks/dlaas/mkl/README.md, stacks/dlaas/oss/README.md, stacks/dlaas/releasenote.md
Align naming for launch and clarify language.
=> updating name to Deep Learning Reference Stack

stacks/dlrs/releasenote.md
Change DLaaS to dlrs when images are available in the docekerhub
Closes: #54
=> Fix release notes nits

stacks/dlrs/mkl/README.md, stacks/dlrs/oss/README.md
Removing parts of the description that do not add value until a
legally-approved description is available that differentiates each
offering. Making formatting changes to enhance the appearance of the
long description. This will ensure that when automated builds occur on
Docker Hub, the description remains correct and does not revert to an
older, non-approved version.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Update README.md for Clear Linux Stacks launch

stacks/dlrs/mkl/README.md, stacks/dlrs/oss/README.md, stacks/dlrs/releasenote.md
=> DLRS release 290

stacks/dlrs/mkl/README.md, stacks/dlrs/mkl/licenses/clear_LICENSE, stacks/dlrs/oss/README.md, stacks/dlrs/oss/licenses/clear_LICENSE, stacks/dlrs/releasenote.md
=> DLRS release 380

stacks/dlrs/mkl/README.md, stacks/dlrs/oss/README.md, stacks/dlrs/releasenote.md
=> DLRS release 500

stacks/dlrs/pytorch/mkl/Dockerfile, stacks/dlrs/pytorch/mkl/README.md, stacks/dlrs/pytorch/mkl/licenses/README.md, stacks/dlrs/pytorch/mkl/licenses/clear_LICENSE, stacks/dlrs/pytorch/mkl/licenses/horovod_LICENSE, stacks/dlrs/pytorch/mkl/licenses/miniconda_LICENSE, stacks/dlrs/pytorch/mkl/licenses/mkl_LICENSE, stacks/dlrs/pytorch/mkl/licenses/pytorch_LICENSE, stacks/dlrs/pytorch/oss/Dockerfile, stacks/dlrs/pytorch/oss/README.md, stacks/dlrs/pytorch/oss/licenses/README.md, stacks/dlrs/pytorch/oss/licenses/clear_LICENSE, stacks/dlrs/pytorch/oss/licenses/horovod_LICENSE, stacks/dlrs/pytorch/oss/licenses/pytorch_LICENSE
=> pytorch: Adds Pytorch based Dockerfiles

README.md, stacks/dlrs/README.md, stacks/dlrs/releasenote.md
modified three files: 
README.md
stacks/dlrs/README.md
stacks/dlrs/releasenotes.md
=> Update Release Collateral for Stacks

.travis.yml, clr-installer-ci/Dockerfile, mixer-ci/Dockerfile, postgresql/Dockerfile, postgresql/README.md, postgresql/bootstrap.sh
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Add Dockerfile for PostgreSQL

stacks/dlrs/mkl/Dockerfile, stacks/dlrs/mkl/README.md, stacks/dlrs/mkl/licenses/clear_LICENSE, stacks/dlrs/oss/Dockerfile, stacks/dlrs/oss/README.md, stacks/dlrs/oss/licenses/clear_LICENSE, stacks/dlrs/pytorch/mkl/Dockerfile, stacks/dlrs/pytorch/mkl/licenses/clear_LICENSE, stacks/dlrs/pytorch/oss/licenses/clear_LICENSE, stacks/dlrs/releasenote.md
Signed-off-by: Daniela Plascencia daniela.plascencia@linux.intel.com
=> DLRS release 1260

.travis.yml, nginx/Dockerfile, nginx/README.md, nginx/default.conf
Signed-off-by: Bin Yang <bin.yang@intel.com>
=> add nginx container

stacks/dlrs/mkl/README.md, stacks/dlrs/mkl/licenses/clear_LICENSE, stacks/dlrs/oss/README.md, stacks/dlrs/oss/licenses/clear_LICENSE, stacks/dlrs/pytorch/mkl/README.md, stacks/dlrs/pytorch/mkl/licenses/clear_LICENSE, stacks/dlrs/pytorch/oss/README.md, stacks/dlrs/pytorch/oss/licenses/clear_LICENSE, stacks/dlrs/releasenote.md
=> DLRS release 1330

stacks/dlrs/mkl/README.md, stacks/dlrs/oss/README.md, stacks/dlrs/pytorch/mkl/README.md, stacks/dlrs/pytorch/oss/README.md, stacks/dlrs/releasenote.md
=> DLRS release 1340

.travis.yml, README.md, redis/Dockerfile, redis/README.md, redis/docker-entrypoint.sh
=> add redis container

.travis.yml, README.md, httpd/Dockerfile, httpd/README.md, httpd/httpd-foreground, httpd/index.html
=> Add httpd container

stacks/dlrs/releasenote.md
Intel Security Center updated its Vulnerability Handling Guidelines,
the verbiage change in the details that must be included when reporting
a potential Security Vulnerability.
https://www.intel.com/content/www/us/en/security-center/vulnerability-handling-guidelines.html
From: "The projects and versions affected"
To: "The products and versions affected"
Verbiage must be updated in the repository to comply SDL requirements
Signed-off-by: Hugo Soto <hugo.a.soto.lopez@intel.com>
=> Update in Reporting Security Vulnerability message

.travis.yml, cgit/Dockerfile, cgit/README.md, cgit/cgitrc, cgit/httpd-cgit.conf
Signed-off-by: Bin Yang <bin.yang@intel.com>
=> add cgit container

.travis.yml, README.md, elasticsearch/Dockerfile, elasticsearch/README.md, elasticsearch/config/elasticsearch.yml, elasticsearch/config/log4j2.properties, elasticsearch/docker-entrypoint.sh
=> Add elasticsearch docker image

.travis.yml, README.md, memcached/Dockerfile, memcached/README.md, memcached/docker-entrypoint.sh
=> Add memcached container

.travis.yml, php/Dockerfile, php/README.md, php/helloworld.php
Signed-off-by: Liu Jianjun <jianjun.liu@intel.com>
=> Add php container

stacks/dlrs/mkl/README.md, stacks/dlrs/mkl/set_env.sh, stacks/dlrs/oss/README.md, stacks/dlrs/pytorch/mkl/Dockerfile, stacks/dlrs/pytorch/mkl/README.md, stacks/dlrs/pytorch/oss/README.md, stacks/dlrs/releasenote.md
=> DLRS release 1390

.travis.yml, node/Dockerfile, node/README.md
Signed-off-by: Liu Jianjun <jianjun.liu@intel.com>
=> add node container

.travis.yml, haproxy/Dockerfile, haproxy/README.md, haproxy/docker-entrypoint.sh, haproxy/haproxy.cfg
=> add haproxy container

.travis.yml, golang/Dockerfile, golang/README.md
=> Add golang container

.travis.yml, iperf/Dockerfile, iperf/README.md
1)correct image name to clearlinux/iperf;
2)add --no-boot-update parameter into swupd update to avoid the container update the boot partition.
=> add iperf microservice based on the individual iperf bundle

haproxy/README.md
=> update haproxy README.md

nginx/README.md
=> The default root directory is /usr/share/nginx/html

stacks/dars/README.md, stacks/dars/mkl/Dockerfile, stacks/dars/mkl/README.md, stacks/dars/mkl/dars.ld.so.conf, stacks/dars/mkl/silent.cfg, stacks/dars/openblas/Dockerfile, stacks/dars/openblas/README.md, stacks/dars/openblas/dars.ld.so.conf
This provides the Data Analytics Reference Stack. To offer more flexibility,
there are two versions of the Data Analytics Reference Stack:
* A Clear Linux derived image optimized for [OpenBLAS](https://www.openblas.net/)
* A Clear Linux derived image optimized for Intel® Math Kernel Library [MKL](https://software.intel.com/en-us/mkl)
=> dars: Introduce the Data Analytics Reference Stack (DARS) Dockerfiles

.travis.yml, openjdk/Dockerfile, openjdk/README.md
=> add openjdk container

.travis.yml, tensorflow/Dockerfile, tensorflow/README.md
=> add tensorflow container

CONTRIBUTING.md
Direct contributors to correct place to look for existing Dockerfiles.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Add reference to Docker library's official images

.travis.yml, rabbitmq/Dockerfile, rabbitmq/README.md
=> add rabbitmq-server container

.travis.yml, perl/Dockerfile, perl/README.md
=> Add perl container

stacks/dars/mkl/Dockerfile, stacks/dars/mkl/README.md, stacks/dars/mkl/profile, stacks/dars/openblas/Dockerfile, stacks/dars/openblas/README.md, stacks/dars/openblas/profile
Commit includes the following changes:
* Less RUN commands (so less intermediate layers)
* Set java11 as default
* Remove spark-core jars files (not required if java11 is default)
=> DARS relase 70

.travis.yml
=> add os-core into .travis.yml file

mariadb/my.cnf
=> Set bind-address in ipv4 foramt to support ipv4 only system

elasticsearch/README.md
The volume esdata should be created first for the example
=> Update elasticsearch README

rabbitmq/Dockerfile, rabbitmq/LICENSE, rabbitmq/docker-entrypoint.sh
=> add entrypoint and LICENSE to run rabbitmq-server

cassandra/Dockerfile, cassandra/README.md, cassandra/docker-entrypoint.sh
Signed-off-by: wangjue <wang.jue@intel.com>
=> Create cassandra microservice

.travis.yml, php-fpm/Dockerfile, php-fpm/README.md, php-fpm/docker-php-entrypoint
=> add php-fpm container

rabbitmq/Dockerfile
=> Add specific rabbitmq-server bundle and use it

cassandra/Dockerfile
Signed-off-by: Wang Jue <wang.jue@intel.com>
=> Add tools/bin to PATH

php-fpm/Dockerfile
=> add bundle curl in php-fpm container

cassandra/Dockerfile, cgit/Dockerfile, elasticsearch/Dockerfile, flink/Dockerfile, golang/Dockerfile, haproxy/Dockerfile, httpd/Dockerfile, iperf/Dockerfile, mariadb/Dockerfile, memcached/Dockerfile, node/Dockerfile, openjdk/Dockerfile, os-core/Dockerfile, perl/Dockerfile, php-fpm/Dockerfile, php/Dockerfile, postgres/Dockerfile, python/Dockerfile, rabbitmq/Dockerfile, redis/Dockerfile, ruby/Dockerfile, tensorflow/Dockerfile
##Signed-off-by: Qi Zheng <qi.zheng@intel.com>
#188
=> Use --no-boot-update instead of --no-scripts

.travis.yml, wordpress/Dockerfile, wordpress/README.md, wordpress/docker-compose.yml, wordpress/docker-entrypoint.sh, wordpress/wordpress.conf
=> add wordpress container

rabbitmq/Dockerfile
=> remove os-core-update from rabbitmq

.travis.yml, tomcat/Dockerfile, tomcat/README.md
=> add apache-tomcat container

tests/CONTRIBUTING.md
=> Add CONTRIBUTING.md for travis tests

mariadb/README.md
=> Update mariadb README

cassandra/Dockerfile, cgit/Dockerfile, httpd/Dockerfile, memcached/Dockerfile, nginx/Dockerfile, nginx/README.md, nginx/default.conf, redis/Dockerfile
=> Add "ARG swupd_args" to make the args really work

cassandra/Dockerfile
=> Add os-core-plus bundle to cassandra Dockerfile

postgres/Dockerfile, postgres/docker-entrypoint.sh
=> Update postgresql from 9 to 11

php-fpm/Dockerfile, wordpress/Dockerfile, wordpress/docker-entrypoint.sh
Once new container images get published, I will check-in the k8s example yaml files
=> Containers update to deploy wordpress on k8s

nginx/README.md
This PR rewrites the nginx README.md to be more comprehensive and hopefully serve as a template for other contaimer image READMEs
=> Update nginx README.md

wordpress/README.md, wordpress/kustomization.yaml, wordpress/mysql-deployment.yaml, wordpress/pv-local.yaml, wordpress/wordpress-deployment.yaml
=> Add wordpress k8s deployment yaml files

wordpress/README.md, wordpress/deploy-local.sh, wordpress/deploy-nfs.sh, wordpress/kustomization.yaml, wordpress/mysql-deployment.yaml, wordpress/nfs-deployment.yaml, wordpress/pv-local.yaml, wordpress/pvc-local.yaml, wordpress/pvc-nfs.yaml, wordpress/rbac.yaml, wordpress/secret.yaml, wordpress/wordpress-deployment.yaml
=> Update the wordpress k8s yaml to support scaling on multi-node cluster

stacks/dlrs/mkl/Dockerfile, stacks/dlrs/mkl/scripts/install_bazel.sh, stacks/dlrs/mkl/scripts/install_tensorflow.sh
=> stacks/dlrs/mkl: version bump v0.4.1

rabbitmq/README.md
=> add deploy cluster nodes into rabbitmq README

cassandra/Dockerfile
Signed-off-by: Wang Jue <wang.jue@intel.com>
=> Remove openjdk src package to decrease package size

mariadb/README.md, mariadb/mariadb-deployment-conf.yaml, mariadb/mariadb-deployment.yaml, memcached/README.md, memcached/memcached-deployment-conf.yaml, memcached/memcached-deployment.yaml, postgres/README.md, postgres/postgres-deployment-conf.yaml, postgres/postgres-deployment.yaml, redis/README.md, redis/redis-deployment-conf.yaml, redis/redis-deployment.yaml
=> Mariadb,Memcached,Postgres,Redis k8s yaml files

cassandra/README.md
=> Update README for deploying cassandra with Kubernetes

cassandra/README.md, cassandra/cassandra-deployment-conf.yaml, cassandra/cassandra-deployment.yaml, cassandra/cassandra-setup.sh, flink/README.md, flink/flink-deployment-conf.yaml, flink/flink-deployment.yaml
=> Cassandra and flink deploy

machine-learning-ui/README.md, machine-learning-ui/machine-learning-ui-deployment.yaml, node/README.md, node/node-deployment.yaml, tomcat/README.md, tomcat/tomcat-deployment-conf-custom.yaml, tomcat/tomcat-deployment-index-custom.yaml, tomcat/tomcat-deployment.yaml
I fixed misses and any recommends?
=> Tomcat, node and ml-ui deploy with k8s

mariadb/Dockerfile
=> Update copy directory for my.cnf

machine-learning-ui/README.md
=> update machine-learning-ui README.md

.travis.yml, tensorflow-serving/Dockerfile, tensorflow-serving/README.md, tensorflow-serving/tf_serving_entrypoint.sh
=> add tensorflow-serving container

mariadb/Dockerfile
=> Fix a typo of two slashes

mariadb/mariadb-deployment-conf.yaml, mariadb/mariadb-deployment.yaml, rabbitmq/README.md, rabbitmq/rabbitmq-deployment-conf.yaml
I  added rabbitmq deploy with k8s and updated mariadb deploy with k8s. Any recommend?
=> Rabbitmq and Mariadb deploy with k8s

golang/README.md, node/README.md, perl/README.md, php/README.md, python/README.md
update the README to include the way to cusomize
the container image with debug capabilities.
=> update README for golang node perl php python

tensorflow-serving/README.md, tensorflow-serving/tensorflow-serving-deployment.yaml
=> Add "tf-serving deploy with k8s"

tensorflow-serving/Dockerfile, tensorflow-serving/tf_serving_entrypoint.sh
=> Add docker run command line arguments support for tensorflow-serving

openvino/docker-entrypoint.sh
=> Fix openvino entrypoint bug

openvino/classification.yaml
=> Fix openvino example yaml file bug

openvino/Dockerfile, openvino/classification.yaml, openvino/docker-compose-server.yml, openvino/docker-compose.yml, openvino/docker-entrypoint.sh, openvino/models.txt
=> Change openvino WORKDIR to /app

stacks/dbrs/releasenote.md
Link to DBRS tutorial was broken, changed to correct destination.
Signed-off-by: Gabriel Briones <gabriel.briones.sayeg@intel.com>
=> Stacks DBRS fix broken link

golang/README.md, node/README.md, perl/README.md, php/README.md, python/README.md
Update reference link to official publish one
=> Update reference link to use official publish one

openvino/models.txt
=> Update the correct model name

openvino/README.md
=> Fix openvino readme typo

tensorflow-serving/README.md
=> update tensorflow-serving README

tensorflow/README.md
=> update tensorflow README

node/Dockerfile, node/docker-entrypoint.sh
=> add node env

node/README.md
=> update node README.md

charts/mariadb/.helmignore, charts/mariadb/Chart.yaml, charts/mariadb/README.md, charts/mariadb/templates/NOTES.txt, charts/mariadb/templates/_helpers.tpl, charts/mariadb/templates/config.yaml, charts/mariadb/templates/deployment.yaml, charts/mariadb/templates/pvc.yaml, charts/mariadb/templates/secrets.yaml, charts/mariadb/templates/service.yaml, charts/mariadb/values.yaml
If there's any miss or faults, I will fix it!
=> Add "Mariadb Deploy with Helm"

charts/mariadb/README.md, charts/node/.helmignore, charts/node/Chart.yaml, charts/node/README.md, charts/node/templates/NOTES.txt, charts/node/templates/_helpers.tpl, charts/node/templates/config.yaml, charts/node/templates/deployment.yaml, charts/node/templates/service.yaml, charts/node/values.yaml
=> Add "Node Deploy with Helm"

openvino/classification.yaml
=> Update yaml file to support k8s 1.16

php/helloworld.php
=> Delete not used helloworld.php

numpy-mp/Dockerfile, numpy-mp/README.md
=> Add numpy-mp

tesseract-ocr/Dockerfile, tesseract-ocr/README.md, tesseract-ocr/hooks/post_push
tesseract is a popular OCR engine with AVX performance optimization
Signed-off-by: jwang <jing.j.wang@intel.com>
=> Add tesseract-ocr container

numpy-mp/Dockerfile, numpy-mp/README.md, numpy-mp/docker-entrypoint.sh, numpy-mp/numpy-mp-demo-deployment.yaml, numpy-mp/set-num-threads.sh
=> add dynamic OMP_NUM_THREADS setting

FaaS/OpenFaaS/template/README.md, FaaS/OpenFaaS/template/python3-clearlinux/Dockerfile, FaaS/OpenFaaS/template/python3-clearlinux/function/handler.py, FaaS/OpenFaaS/template/python3-clearlinux/index.py, FaaS/OpenFaaS/template/python3-clearlinux/template.yml
=> Add OpenFaaS Clear Linux based python3 template

FaaS/OpenFaaS/template/README.md, FaaS/OpenFaaS/template/dockerfile-clearlinux/Dockerfile, FaaS/OpenFaaS/template/dockerfile-clearlinux/function/Dockerfile, FaaS/OpenFaaS/template/dockerfile-clearlinux/template.yml
=> Add OpenFaaS dockerfile template

FaaS/OpenFaaS/template/README.md, FaaS/OpenFaaS/template/go-clearlinux/Dockerfile, FaaS/OpenFaaS/template/go-clearlinux/function/handler.go, FaaS/OpenFaaS/template/go-clearlinux/main.go, FaaS/OpenFaaS/template/go-clearlinux/template.yml
Signed-off-by: Sophia Gong <sophia.gong@intel.com>
=> Add OpenFaaS Clear Linux based GO template

gonum/Dockerfile, gonum/README.md, gonum/test/blas_test.go
Gonum is a set of numeric libraries for the Go programming language. By netlib interface, it can
use CBLAS which has AVX-512 optimization for better performance
Signed-off-by: jwang <jing.j.wang@intel.com>
=> Add gonum container

numpy-mp/README.md, numpy-mp/set-num-threads.sh
=> adaptive v2 for cpuset and update README

numpy-mp/README.md, numpy-mp/numpy-mp-demo-deployment.yaml
=> update README for kubernetes deployment

openvino/README.md, openvino/classification.yaml, openvino/demo.sh, openvino/docker-compose-server.yml, openvino/docker-compose.yml
This model could show AVX512 VNNI performance advantage.
=> Update sample model to mobilenetv2-int8-tf-0001

openvino/README.md
=> Update Openvino README.md

wordpress/Dockerfile
=> update wordpress docker container

numpy-mp/README.md, numpy-mp/docker-entrypoint.sh
=> numpy-mp:update README and remove debug information

tests/ruby/ruby-security.bats
=> Fix ruby security check failure issue

openvino/README.md
=> Update openvino README for GPU plugin

numpy-mp/set-num-threads.sh
=> add multi-socket support for adaptive script

python/Dockerfile, python/README.md
=> add python env
